[project]
name = "ecotwin-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.110.0",
  "uvicorn[standard]==0.29.0",
  "pydantic==2.6.4",
  "influxdb-client==1.43.0",
]

[tool.uvicorn]
factory = false
